labels:
  - name: 'status: template-invalid'
    labeled:
      issue:
        body: |
          @{{issue.user.login}}, please follow the issue template.
        action: close
      pr:
        body: |
          @{{pull_request.user.login}}, please follow the pull request template.
        action: close
    unlabeled:
      issue:
        body: Thank you for following the template. The thread is now re-opened.
        action: open
  - name: duplicate
    labeled:
      issue:
        body: This issue already exists.
        action: close
      pr:
        body: This pull request already exists.
        action: close
  - name: 'status: locked'
    labeled:
      issue:
        body: |
          This issue has been **LOCKED** because of bad chat!

          Please do not spam messages or send offensive messages.
        action: close
        locking: lock
        lock_reason: spam
      pr:
        body: |
          This pull-request has been **LOCKED** because of bad chat!

          Please do not spam messages or send offensive messages.
        action: close
        locking: lock
        lock_reason: spam
    unlabeled:
      issue:
        body: |
          This issue has been unlocked now.
        locking: unlock
      pr:
        body: |
          This pull-request has been unlocked now.
        action: open
        locking: unlock
  - name: 'status: cannot-reproduce'
    labeled:
      issue:
        body: |
          @{{issue.user.login}}, please check the reproduction step, it is not working.
        action: close
    unlabeled:
      issue:
        body: |
          Thank you for fixing reproduction steps. The thread is now re-opened.
        locking: open
