import Head from 'next/head';
// import { Header } from '@inc/ui';

const Home = () => (
  <>
    <Head>
      <title>Team C</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    Hello World!
  </>
);

export default Home;
