import Head from 'next/head';
import AdminFigure from '../../components/AdminFigure';
import Sidebar, { adminSidebar } from '../../components/Sidebar/Sidebar';
import SearchBar from '../../components/SearchBar';

const Home = () => (
  <div className="bg-[#FAFAFA]">
    <Head>
      <title>Team B</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Sidebar sidebarList={adminSidebar} selected="Users">
        <div className="flex flex-col w-full h-full overflow-auto gap-8 p-8">
          <div className="flex flex-col h-full border gap-8">
            {/* { replace this with sidebar } */}
            <div className="bg-base-100 border w-full h-20 shadow-lg rounded-2xl" />

            <div className="flex flex-row gap-8">
              <AdminFigure title="Registered Companies" value="1,234" color="text-primary" />
              <AdminFigure title="Total Users" value="4,568" color="text-accent" />
              <AdminFigure title="Pending Invites" value="5,983" color="text-secondary" />
            </div>

            <div className="flex flex-row gap-8">
              <div className="flex w-7/12">
                <div className="bg-base-100 w-full h-fit shadow-lg rounded-2xl">
                  <div className="flex flex-row justify-between items-center gap-8 p-6">
                    <div className="flex flex-col">
                      <h1 className="text-xl font-bold">Registered Users</h1>
                      <p>Showing 1-8 of 22 users</p>
                    </div>
                    <div className="flex flex-col gap-4">
                      <SearchBar placeholder="Search by e-mail" />
                    </div>
                  </div>
                  <div className="w-full h-px bg-base-300" />
                  {/* replace with table component */}
                  <div className="flex flex-col justify-between items-center">
                    <div className="flex flex-row justify-between h-8 bg-secondary items-center gap-8 px-8 w-full">
                      <div className="flex flex-row items-center">
                        <div className="h-px w-20" />
                        <p className="text-base-100">User</p>
                      </div>
                      <p className="text-base-100">E-mail</p>
                      <p className="text-base-100">Company</p>
                      <p className="text-base-100">Mobile Number</p>
                      <p className="text-base-100">Actions</p>
                    </div>
                    <div className="flex flex-row justify-between h-16 items-center gap-8 px-8 w-full">
                      <div className="flex flex-row items-center">
                        <div className="h-9 w-9 mr-11 rounded-full bg-base-300" />
                        <p>AHH</p>
                      </div>
                      <p>AHH</p>
                      <p>AHH</p>
                      <p>AHH</p>
                      <p className="mr-4">AHH</p>
                    </div>
                  </div>
                  <div className="w-full h-px bg-base-300" />
                  <div className="flex flex-row justify-end gap-8 p-6">
                    <div className="btn-group">
                      <button className="btn bg-secondary border-secondary">1</button>
                      <button className="btn">2</button>
                      <button className="btn">3</button>
                    </div>
                  </div>
                </div>
              </div>

              <div className="flex w-5/12">
                <div className="bg-base-100 w-full h-fit shadow-lg rounded-2xl">
                  <div className="flex flex-row justify-between items-center gap-8 p-6">
                    <div className="flex flex-col">
                      <h1 className="text-xl font-bold">Registered Users</h1>
                      <p>Showing 1-8 of 22 users</p>
                    </div>
                    <div className="flex flex-col gap-4">
                      <SearchBar placeholder="Search by e-mail" />
                    </div>
                  </div>
                  <div className="w-full h-px bg-base-300" />
                  {/* replace with table component */}
                  <div className="flex flex-col justify-between items-center">
                    <div className="flex flex-row justify-between h-8 bg-secondary items-center gap-8 px-8 w-full">
                      <div className="flex flex-row items-center">
                        <div className="h-px w-20" />
                        <p className="text-base-100">User</p>
                      </div>
                      <p className="text-base-100">E-mail</p>
                      <p className="text-base-100">Company</p>
                      <p className="text-base-100">Mobile Number</p>
                      <p className="text-base-100">Actions</p>
                    </div>
                    <div className="flex flex-row justify-between h-16 items-center gap-8 px-8 w-full">
                      <div className="flex flex-row items-center">
                        <div className="h-9 w-9 mr-11 rounded-full bg-base-300" />
                        <p>AHH</p>
                      </div>
                      <p>AHH</p>
                      <p>AHH</p>
                      <p>AHH</p>
                      <p className="mr-4">AHH</p>
                    </div>
                  </div>
                  <div className="w-full h-px bg-base-300" />
                  <div className="flex flex-row justify-end gap-8 p-6">
                    <div className="btn-group">
                      <button className="btn bg-secondary border-secondary">1</button>
                      <button className="btn">2</button>
                      <button className="btn">3</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Sidebar>
    </main>
  </div>
);

export default Home;
