import Head from 'next/head';
import pic from '../public/siwma-logo-sm.png';
import AdminFigure from '../components/AdminFigure';
import BaseTable from '../components/Tables/BaseTable';

const Home = () => {
  const data = [
    {
      id: 1,
      profilePicture: pic,
      name: 'John Doe',
      email: 'john@doe.com',
      company: 'Company',
      mobileNumber: '12345678',
    },
    {
      id: 2,
      profilePicture: pic,
      name: 'Veryvery Long Name',
      email: 'veryverylongname@veryverylongdomain.com',
      company: 'Company',
      mobileNumber: '12345678',
    },
  ];

  return (
    <div className="bg-[#FAFAFA]">
      <Head>
        <title>Team B</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row w-full h-full gap-8">
        <div className="bg-white shadow-xl rounded-lg p-4 w-2/12 h-full" />
        <div className="flex flex-row flex-wrap w-full h-full gap-8 p-8">
          <AdminFigure title="Registered Companies" value="1,234" color="text-primary" />
          <AdminFigure title="Total Users" value="4,568" color="text-accent" />
          <AdminFigure title="Pending Invites" value="5,983" color="text-secondary" />
        </div>
      </div>
      <div className="flex flex-row w-4/5">
        <BaseTable data={data} />
      </div>
    </div>
  );
};

export default Home;
