import Head from 'next/head';
import Image from 'next/image';
import { Header } from '@inc/ui';
import styles from '../styles/Home.module.css';

const Home = () => (
  <div className={styles.container}>
    <Head>
      <title>Team B</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}></main>
  </div>
);

export default Home;
