name: 'CI stuff'

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]

env:
  PNPM_VERSION: 7.14.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2.5.0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - run: npm i -g pnpm@${PNPM_VERSION}

      - run: pnpm install

      - run: pnpm run build

      # - uses: actions/cache@v3
      #   id: cache-build
      #   with:
      #     path: ./*
      #     key: ${{ github.sha }}-${{ github.run_number }}

  # lint:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout source tree
  #       uses: actions/checkout@v2.5.0

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '16.x'

  #     - run: npm i -g pnpm@${PNPM_VERSION}

  #     - uses: actions/cache@v3
  #       id: restore-build
  #       with:
  #         path: ./*
  #         key: ${{ github.sha }}-${{ github.run_number }}

  #     - run: pnpm run lint
