name: 'CI stuff'

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]

env:
  PNPM_VERSION: 7.14.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2.5.0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Installing PNPM
        run: npm i -g pnpm@${PNPM_VERSION}

      - name: Installing dependencies
        run: pnpm install

      - name: Create .env.local for admin
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          envkey_NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          envkey_NEXT_PUBLIC_SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          directory: apps/admin/
          file_name: .env.local
          fail_on_empty: true

      - name: Create .env.local for web
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          envkey_NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          envkey_NEXT_PUBLIC_SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          directory: apps/web/
          file_name: .env.local
          fail_on_empty: true

      - run: pnpm run build

      # - uses: actions/cache@v3
      #   id: cache-build
      #   with:
      #     path: ./*
      #     key: ${{ github.sha }}-${{ github.run_number }}

  # lint:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout source tree
  #       uses: actions/checkout@v2.5.0

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: '16.x'

  #     - run: npm i -g pnpm@${PNPM_VERSION}

  #     - uses: actions/cache@v3
  #       id: restore-build
  #       with:
  #         path: ./*
  #         key: ${{ github.sha }}-${{ github.run_number }}

  #     - run: pnpm run lint
